- cmd/age/age.go
- cmd/age/parse.go
- internal/age/ssh.go
Signed-off-by: Matt Layher <mdlayher@gmail.com>
This is primitive and only currently accepts SSH recipients via public key text (rather than file), but it seems to work!
```
$ echo "hello SSH" | ./age "`cat test_rsa.pub`" "`cat test_ed25519.pub`" | tee ssh.age
This is a file encrypted with age-tool.com, version 1
-> ssh-rsa X2Vtsw
h5ntTt0PEBcZgtgtjGu0Gxj1DtbJqLVt-9MrYmsgGxNPIy9kL3Dn5vJf61axbBo0OyjBUtSGvpXXRYFazJfWuIj1LeJhnCyK0jLZ5dRPDrVNtT1NqMzlY_Lh9IiNg-V37FLWxCJOkmDO7yYz1URRSnRiurgVfj--emUaBvvc0053ABWE7WOTlmHssQOp8dnjrh3Q6lsOeklLsHnLtahkOS8lqmPs0GH3bx--0calWABTGYktXr3-YJz8-i19b4a-IHBo57BYI3XT9p8KC4dHOdUdt_1r0jriZmdpSj2_2Z3vAdvzH8LbOaXDh1A76ec1LuQL63SUKNEHTChuShi3qg
-> ssh-ed25519 lSfeAQ gwegE4mWBU82XFV3U_9TUY_fZLV1Ps81kLWIcCmFGTA
J355AxSwjGDogzlNxY0yrCRtSNSJ7BNreC5GsmRlUB8
--- …
```
> cmd/age: initial support for SSH identities and recipients

- cmd/age/age.go
For consistency across all options.
> Provide a `--output` option.

- README.md
Since Homebrew now works on linux (https://docs.brew.sh/Homebrew-on-Linux), you can use the same installation steps for Linux as you would for macOS. I tested this on Ubuntu 19.10.
> Installation: mention Linux for Homebrew

- .cirrus.yml
Example run: https://cirrus-ci.com/build/5764596254375936
> .cirrus.yml: enable Cirrus-CI for FreeBSD CI

- README.md
Without the `-d` option, the command gives the following error: 
```
Error: -i/--identity can't be used in encryption mode.
Did you forget to specify -d/--decrypt?
[ Did age not do what you expected? Could an error be more useful? Tell us: https://filippo.io/age/report ]
```
Hope this helps!
> Fixing a small typo in the SSH Keys section

- README.md
Update readme with Arch Linux AUR instructions.
> README: add Arch Linux AUR instructions.

- internal/bech32/bech32_test.go
> Use explicit conversion to avoid go-test error

- internal/stream/stream.go
it seems that r.c was renamed to r.src
> fixed function documentation

- cmd/age-keygen/keygen.go
`age-keygen` didn't support the `--output` option it documented -- the option simply wasn't defined. This PR fixes that.
The whitespace change is to make the structure of `cmd/age-keygen.main` more closely match the structure of `cmd/age.main`.
> cmd/age-keygen: add --output option as an alias for -o

- cmd/age/age.go
Previously output was buffered when `--armor` was set and the output was a TTY. It was not checked whether the input was a TTY, decryption was not taken into account and binary output was not buffered either. This lead to some problems:
1.: `dd if=/dev/urandom bs=1M count=300 | age -r age1... -a` caused `fatal error: runtime: out of memory` (increase count if it doesn't for you). No one will encrypt this much to stdout, but buffering is unnecessary here.
2.: Output was not buffered for `age -d` (when pasting some armored input into the TTY as input). Admittedly this only happens when copy and pasting a lot of input (ca. 70k bytes for me), but it still seems wrong. Here is how I can make the problem visible:
```
yes 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod …
```
> cmd/age: Improve decision on when to buffer output

- cmd/age-keygen/keygen.go
- cmd/age/age.go
- cmd/age/encrypted_keys.go
- go.mod
According to the [documentation of golang.org/x/crypto/ssh/terminal](https://pkg.go.dev/golang.org/x/crypto/ssh/terminal) this package has been deprecated and golang.org/x/term should be used instead.
> Use golang.org/x/term instead of deprecated package

- README.md
I've moved age to the official repositories: https://archlinux.org/packages/community/x86_64/age/
> README: mention official Arch Linux package

- README.md
The extra `-yu` arguments here don't belong on a command to install a specific package. Just `-S` is correct to install a single package. The `-u` upgrades all the rest of the packages on the system, something the user may or may not want to do at that moment. The `-y` updates the package indexes, but because Arch does not support partial updates that should **not** be run except when doing a system update. To install a single package at the version that matches your current system just sync the package using the index you have. If you have an old index and do need to update, that's something Arch expects you to understand and do on your own.
> Drop system upgrade args from Arch Linux install

- doc/age.1.ronn
Changed `succesful` to `successful`.
> doc: fix typo in age(1)

- .github/workflows/build.yml
Environmental secrets are not shared to workflows run from forks without extra work by Maintainers. 
The existing build workflow uses a secret to sign windows exe's and is breaking for all external PRs. 
Builds are also probably unnecessary for PRs.
See: https://github.com/FiloSottile/age/pull/353#issuecomment-997159334
> Skip signing if key pass isn't available

- age_test.go
- armor/armor_test.go
- cmd/age/age_test.go
- cmd/age/parse.go
The `io/ioutil` package has been deprecated in Go 1.16 (See https://golang.org/doc/go1.16#ioutil). Since age has been upgraded to Go 1.17 in 36b0a4f6117c9ee7210207a69de2eab36b650869, this PR replaces the existing `io/ioutil` functions with their new definitions in `io` and `os` packages.
> refactor: move from io/ioutil to io and os packages

- README.md
[Scoop](https://scoop.sh/) is a package manager for Windows, similar to Chocolatey. However, Scoop installs as the user instead of as admin, and installs binaries in custom locations such as ~\scoop\apps instead of C:\Program Files etc.
> Add Scoop package to README

- cmd/age-keygen/keygen.go
Shouldn't this function call os.exit as age errorf does?
https://github.com/FiloSottile/age/blob/e4ae4cf884753cbed766b9522902c2a9dd556468/cmd/age/age.go#L409
> cmd/age-keygen: errorf calls os.exit

- README.md
Since Go changed their site from golang.org to go.dev a while ago.
> change Go download link from golang.org to go.dev

- internal/format/format.go
Not sure if it's a good idea to include the last `age` version that is able to decrypt this kind of messages, but it seemed useful to me. Feel free to update this proposal to match the project style.
> Improve error message for old header format

- cmd/age/encrypted_keys.go
As mention here [0], I had a problem when /dev/tty exists, but age failed to open it. Now age falls back to /dev/tty, which is the same behavior as if /dev/tty does not exist.
If there are additional changes needed, I am happy to implement them.
PS: Thank you very much for this great tool!
[0] https://github.com/FiloSottile/age/issues/279#issuecomment-1115499664
> cmd/age: also fallback to stdin and stdout, if /dev/tty exists, but cannot be opened

- .github/workflows/build.yml
From the release [v1.1.0-rc.1](https://github.com/FiloSottile/age/releases/tag/v1.1.0-rc.1) you can see `<a href="https://go.dev/LICENSE?m=text">Moved Permanently</a>.` at the end of the final (packaged) LICENSE file.
This change addresses this issue.
> .github/workflows: change Go LICENSE URL from golang.org to go.dev

- .github/workflows/build.yml
Uses [`gh release upload`](https://cli.github.com/manual/gh_release_upload) for the sake of pipeline code golfing, if that's a thing.
> .github/workflows: use gh to upload release artifacts

- go.mod
- go.sum
- testkit_test.go
Makes it easier for package builders with no networking (e.g Nixpkgs) to vendor modules and run tests without further need of network access.
Will update the pseudo versions in this PR once https://github.com/C2SP/CCTV/pull/2 merges.
> age: depend on c2sp.org/CCTV/age

- README.md
https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#specifying-the-theme-an-image-is-shown-to
I have used svg logos inside `logo/` folder only to preview the final render when switching between dark/light theme.
> README: dark/light mode logo

- .github/workflows/interop.yml
After cli/cli#6614, `gh api` can be used with nested object fields. 💅🏼 [^1]
> **Note** includes 79cc0644c2eacabb212740ec3ef11290220b4c01 with a pedantic change that doesn’t provide any security benefit on a public repository; can be dropped upon request.
[^1]: 🟩
> .github/workflows: trigger interoperability tests using gh

- .github/workflows/build.yml
Running `actions/setup-go` before `actions/checkout` was preventing the former from using `go.sum` to cache dependencies, as it wasn't still present in the working directory:
```
Restore cache failed: Dependencies file is not found in /home/runner/work/age/age. Supported file pattern: go.sum
```
> .github/workflows: fix actions/setup-go cache
